version: '3'

services:
  db:
    container_name: db
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
#    command: ["postgres", "-c", "log_statement=all"]

  server:
    container_name: server
    restart: always
    build:
      context: ./server
    ports:
      - "80:80"
    depends_on:
      - db